; German texts of cargo-packager's NSIS installer (keys as in its English.nsh).
; UTF-8 with BOM: NSIS reads a file without BOM in the system code page.
LangString addOrReinstall ${LANG_GERMAN} "Komponenten hinzufügen oder neu installieren"
LangString alreadyInstalled ${LANG_GERMAN} "Bereits installiert"
LangString alreadyInstalledLong ${LANG_GERMAN} "${PRODUCTNAME} ${VERSION} ist bereits installiert. Wähle, was geschehen soll, und klicke auf Weiter."
LangString appRunning ${LANG_GERMAN} "${PRODUCTNAME} läuft noch! Bitte schließe es und versuche es dann noch einmal."
LangString appRunningOkKill ${LANG_GERMAN} "${PRODUCTNAME} läuft noch!$\nKlicke auf OK, um es zu beenden."
LangString chooseMaintenanceOption ${LANG_GERMAN} "Wähle, was geschehen soll."
LangString choowHowToInstall ${LANG_GERMAN} "Wähle, wie ${PRODUCTNAME} installiert werden soll."
LangString createDesktop ${LANG_GERMAN} "Verknüpfung auf dem Desktop anlegen"
LangString dontUninstall ${LANG_GERMAN} "Nicht deinstallieren"
LangString dontUninstallDowngrade ${LANG_GERMAN} "Nicht deinstallieren (eine ältere Version ohne Deinstallation zu installieren ist hier abgeschaltet)"
LangString failedToKillApp ${LANG_GERMAN} "${PRODUCTNAME} ließ sich nicht beenden. Bitte schließe es und versuche es dann noch einmal."
LangString installingWebview2 ${LANG_GERMAN} "WebView2 wird installiert …"
LangString newerVersionInstalled ${LANG_GERMAN} "Eine neuere Version von ${PRODUCTNAME} ist bereits installiert! Eine ältere Version darüber zu installieren wird nicht empfohlen. Wenn du wirklich diese ältere Version willst, deinstalliere besser zuerst die aktuelle. Wähle, was geschehen soll, und klicke auf Weiter."
LangString older ${LANG_GERMAN} "ältere"
LangString olderOrUnknownVersionInstalled ${LANG_GERMAN} "Eine $R4 Version von ${PRODUCTNAME} ist installiert. Es wird empfohlen, sie vor der Installation zu deinstallieren. Wähle, was geschehen soll, und klicke auf Weiter."
LangString silentDowngrades ${LANG_GERMAN} "Ältere Versionen lassen sich mit diesem Installer nicht still installieren. Bitte nutze die grafische Installation.$\n"
LangString unableToUninstall ${LANG_GERMAN} "Deinstallation nicht möglich!"
LangString uninstallApp ${LANG_GERMAN} "${PRODUCTNAME} deinstallieren"
LangString uninstallBeforeInstalling ${LANG_GERMAN} "Vor der Installation deinstallieren"
LangString unknown ${LANG_GERMAN} "unbekannte"
LangString deleteAppData ${LANG_GERMAN} "Anwendungsdaten löschen"
