; Italian texts of cargo-packager's NSIS installer (keys as in its English.nsh).
; UTF-8 with BOM: NSIS reads a file without BOM in the system code page.
LangString addOrReinstall ${LANG_ITALIAN} "Aggiungi o reinstalla componenti"
LangString alreadyInstalled ${LANG_ITALIAN} "Già installato"
LangString alreadyInstalledLong ${LANG_ITALIAN} "${PRODUCTNAME} ${VERSION} è già installato. Scegli l'operazione da eseguire e fai clic su Avanti."
LangString appRunning ${LANG_ITALIAN} "${PRODUCTNAME} è in esecuzione! Chiudilo e riprova."
LangString appRunningOkKill ${LANG_ITALIAN} "${PRODUCTNAME} è in esecuzione!$\nFai clic su OK per chiuderlo."
LangString chooseMaintenanceOption ${LANG_ITALIAN} "Scegli l'operazione di manutenzione da eseguire."
LangString choowHowToInstall ${LANG_ITALIAN} "Scegli come installare ${PRODUCTNAME}."
LangString createDesktop ${LANG_ITALIAN} "Crea un collegamento sul desktop"
LangString dontUninstall ${LANG_ITALIAN} "Non disinstallare"
LangString dontUninstallDowngrade ${LANG_ITALIAN} "Non disinstallare (installare una versione precedente senza disinstallare è disattivato in questo programma di installazione)"
LangString failedToKillApp ${LANG_ITALIAN} "Impossibile chiudere ${PRODUCTNAME}. Chiudilo e riprova."
LangString installingWebview2 ${LANG_ITALIAN} "Installazione di WebView2 …"
LangString newerVersionInstalled ${LANG_ITALIAN} "È già installata una versione più recente di ${PRODUCTNAME}! Installare una versione precedente è sconsigliato. Se vuoi davvero questa versione precedente, è meglio disinstallare prima quella attuale. Scegli l'operazione da eseguire e fai clic su Avanti."
LangString older ${LANG_ITALIAN} "precedente"
LangString olderOrUnknownVersionInstalled ${LANG_ITALIAN} "Sul sistema è installata una versione $R4 di ${PRODUCTNAME}. Si consiglia di disinstallarla prima dell'installazione. Scegli l'operazione da eseguire e fai clic su Avanti."
LangString silentDowngrades ${LANG_ITALIAN} "Questo programma di installazione non installa versioni precedenti in modalità silenziosa. Usa l'installazione grafica.$\n"
LangString unableToUninstall ${LANG_ITALIAN} "Impossibile disinstallare!"
LangString uninstallApp ${LANG_ITALIAN} "Disinstalla ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ITALIAN} "Disinstalla prima di installare"
LangString unknown ${LANG_ITALIAN} "sconosciuta"
LangString deleteAppData ${LANG_ITALIAN} "Elimina i dati dell'applicazione"
