"""Cuts Cerno's app icon out of its source image and writes the icon files.

The source (`assets/icon-source.jpg`, generated by an image model) is a JPEG: the
"transparent" checkerboard around the rounded tile is baked into the pixels. The tile is
blue, the checkerboard and the aperture are white or light grey, so a pixel belongs to the
tile when blue exceeds red by more than THRESHOLD; everything outside that is reachable from
the image border becomes transparent (the white aperture inside the tile stays). A source
that already has transparency (PNG) keeps its alpha. The tile is centred on a square canvas with TILE_SHARE of its width, and every size is resized from that
master in one step (Pillow premultiplies alpha, so no light fringe).

Writes into <out dir>:
  icon.png  256 px – window and taskbar icon, embedded by `src/main.rs`
  icon.ico  16–256 px – the exe's icon, embedded by `build.rs` on Windows

    python tools/make_icon.py assets/icon-source.jpg assets
"""

import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

# Blue minus red: the tile is 63 and more (dark corner), the checkerboard at most 17.
THRESHOLD = 45
# Share of the canvas the tile's longer side covers (Windows icons leave a small margin).
TILE_SHARE = 0.875
ICO_SIZES = [16, 20, 24, 32, 40, 48, 64, 96, 128, 256]
PNG_SIZE = 256


def cut_out(source: Image.Image) -> Image.Image:
    if source.mode in ("RGBA", "LA") and source.getextrema()[-1][0] < 255:
        # Already transparent around the tile: keep its alpha, only centre it.
        tile = source.convert("RGBA")
        return centred(tile.crop(tile.getbbox(alpha_only=True)))

    rgb = np.asarray(source.convert("RGB"))
    blue = rgb[..., 2].astype(int) - rgb[..., 0].astype(int)
    # `copy()`: an image from `fromarray` shares the array's memory, and Pillow 12's
    # floodfill then silently changes nothing.
    not_tile = Image.fromarray(np.where(blue > THRESHOLD, 0, 255).astype(np.uint8)).copy()
    ImageDraw.floodfill(not_tile, (0, 0), 128)
    outside = np.asarray(not_tile) == 128
    if outside.all() or not outside[0].all():
        sys.exit("no tile found: the image border must be background")

    rgba = np.dstack([rgb, np.where(outside, 0, 255).astype(np.uint8)])
    rgba[outside, :3] = 0
    ys, xs = np.nonzero(~outside)
    left, top, right, bottom = xs.min(), ys.min(), xs.max() + 1, ys.max() + 1
    return centred(Image.fromarray(rgba, "RGBA").crop((left, top, right, bottom)))


def centred(tile: Image.Image) -> Image.Image:
    side = round(max(tile.size) / TILE_SHARE)
    canvas = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    canvas.paste(tile, ((side - tile.width) // 2, (side - tile.height) // 2))
    return canvas


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    master = cut_out(Image.open(sys.argv[1]))
    out = Path(sys.argv[2])
    out.mkdir(parents=True, exist_ok=True)

    def sized(size: int) -> Image.Image:
        return master.resize((size, size), Image.Resampling.LANCZOS)

    sized(PNG_SIZE).save(out / "icon.png", optimize=True)
    frames = [sized(size) for size in ICO_SIZES]
    frames[-1].save(
        out / "icon.ico",
        sizes=[(size, size) for size in ICO_SIZES],
        append_images=frames[:-1],
    )
    print(f"master {master.width} px -> {out / 'icon.png'}, {out / 'icon.ico'}")


if __name__ == "__main__":
    main()
